FROM ubuntu:19.04 

COPY github-builder.php /var/www/html/github-builder.php
COPY config.php /var/www/html/config.php
COPY composer.json /var/www/html/composer.json

LABEL maintainer="newsworthy39@github.com"

ENV PHP_VERSION=7.2 \
    PHP_FPM_USER=www-data \
    COMPOSER_AUTH='{"github-oauth": {"github.com": "eae69c067063f5eb3de450739a38eca6ee6cc74c" }}'

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      php${PHP_VERSION}-cli php${PHP_VERSION}-gd \
      php${PHP_VERSION}-pgsql php${PHP_VERSION}-mysql php${PHP_VERSION}-xml \
      php${PHP_VERSION}-mbstring composer php${PHP_VERSION}-zip git unzip \
      && mkdir -p /run/php/ && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html/

RUN composer install --no-dev